apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collabmd.fullname" . }}
  labels:
    {{- include "collabmd.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ printf "%v" .Values.config.port | quote }}
  COLLABMD_VAULT_DIR: {{ .Values.config.vaultDir | quote }}
  BASE_PATH: {{ .Values.config.basePath | quote }}
  PUBLIC_BASE_URL: {{ .Values.config.publicBaseUrl | quote }}
  PUBLIC_WS_BASE_URL: {{ .Values.config.publicWsBaseUrl | quote }}
  WS_BASE_PATH: {{ .Values.config.wsBasePath | quote }}
  PLANTUML_SERVER_URL: {{ ternary (printf "http://%s:%v" (include "collabmd.plantumlFullname" .) .Values.plantuml.service.port) .Values.config.plantumlServerUrl .Values.plantuml.enabled | quote }}
  HTTP_KEEP_ALIVE_TIMEOUT_MS: {{ printf "%v" .Values.config.httpKeepAliveTimeoutMs | quote }}
  HTTP_HEADERS_TIMEOUT_MS: {{ printf "%v" .Values.config.httpHeadersTimeoutMs | quote }}
  HTTP_REQUEST_TIMEOUT_MS: {{ printf "%v" .Values.config.httpRequestTimeoutMs | quote }}
  WS_HEARTBEAT_INTERVAL_MS: {{ printf "%v" .Values.config.wsHeartbeatIntervalMs | quote }}
  WS_MAX_BUFFERED_AMOUNT_BYTES: {{ int64 .Values.config.wsMaxBufferedAmountBytes | quote }}
  WS_MAX_PAYLOAD_BYTES: {{ int64 .Values.config.wsMaxPayloadBytes | quote }}
  AUTH_STRATEGY: {{ .Values.auth.strategy | quote }}
  AUTH_SESSION_MAX_AGE_MS: {{ printf "%v" .Values.auth.sessionMaxAgeMs | quote }}
  AUTH_OIDC_ALLOWED_EMAILS: {{ .Values.auth.oidc.allowedEmails | quote }}
  AUTH_OIDC_ALLOWED_DOMAINS: {{ .Values.auth.oidc.allowedDomains | quote }}
  COLLABMD_GIT_ENABLED: {{ ternary "true" "false" .Values.git.enabled | quote }}
  COLLABMD_GIT_REPO_URL: {{ .Values.git.repoUrl | quote }}
  COLLABMD_GIT_USER_NAME: {{ .Values.git.userName | quote }}
  COLLABMD_GIT_USER_EMAIL: {{ .Values.git.userEmail | quote }}
  COLLABMD_GIT_SSH_PRIVATE_KEY_FILE: {{ ternary .Values.git.ssh.mountPaths.privateKeyFile "" (ne .Values.git.ssh.privateKeyFileSecret "") | quote }}
  COLLABMD_GIT_SSH_KNOWN_HOSTS_FILE: {{ ternary .Values.git.ssh.mountPaths.knownHostsFile "" (ne .Values.git.ssh.knownHostsSecret "") | quote }}
